const data = [
	{
		id: 1,
		name: "Toyota RAV4",
		info1:"https://static.vecteezy.com/system/resources/previews/000/643/326/original/vector-group-people-icon.jpg",
		p1:"    4People",
		info2:"https://cdn0.iconfinder.com/data/icons/jumpicon-energy-glyph/32/-_Gas-Station-Petrol-Fuel-Oil-Pump-512.png",
		p2:"Gasoline",
		info3:"https://pic.onlinewebfonts.com/svg/img_128549.png",
		p3:"5.3km/lit.",
		info4:"https://cdn3.iconfinder.com/data/icons/driver-wheel/154/car-auto-drive-driver-wheel-512.png",
		p4:"Automatic",
		image: "https://www.motortrend.com/uploads/sites/5/2016/12/2017-Toyota-RAV4-SE-front-three-quarter-in-motion-02-e1502926043520.jpg",
		price: "$440/month",
	},
	{
		id: 2,
		name: "BMW 3 Series",
		info1:"https://static.vecteezy.com/system/resources/previews/000/643/326/original/vector-group-people-icon.jpg",
		p1:"    4People",
		info2:"https://cdn0.iconfinder.com/data/icons/jumpicon-energy-glyph/32/-_Gas-Station-Petrol-Fuel-Oil-Pump-512.png",
		p2:"Gasoline",
		info3:"https://pic.onlinewebfonts.com/svg/img_128549.png",
		p3:"5.3km/lit.",
		info4:"https://cdn3.iconfinder.com/data/icons/driver-wheel/154/car-auto-drive-driver-wheel-512.png",
		p4:"Automatic",
		image: "https://assets-eu-01.kc-usercontent.com/bb5aba31-d98c-0160-8548-418b3723c58e/8ed3765c-1c03-46f5-8a0a-d6a5b5c636da/BMW%203%20Series%20(5).jpg",
		price: "$350/month",
	},
	{
		id: 3,
		name: "Volkswagen T-Cross",
		info1:"https://static.vecteezy.com/system/resources/previews/000/643/326/original/vector-group-people-icon.jpg",
		p1:"    4People",
		info2:"https://cdn0.iconfinder.com/data/icons/jumpicon-energy-glyph/32/-_Gas-Station-Petrol-Fuel-Oil-Pump-512.png",
		p2:"Gasoline",
		info3:"https://pic.onlinewebfonts.com/svg/img_128549.png",
		p3:"5.3km/lit.",
		info4:"https://cdn3.iconfinder.com/data/icons/driver-wheel/154/car-auto-drive-driver-wheel-512.png",
		p4:"Automatic",
		image: "https://i.auto-bild.de/ir_img/1/5/7/6/1/2/9/VW-T-Cross-2019-Bildergalerie-1200x800-aa390e8cecfc05e9.jpg",
		price: "$400/month",
	},
	{
		id: 4,
		name: "Cadillac Escalade",
		info1:"https://static.vecteezy.com/system/resources/previews/000/643/326/original/vector-group-people-icon.jpg",
		p1:"    4People",
		info2:"https://cdn0.iconfinder.com/data/icons/jumpicon-energy-glyph/32/-_Gas-Station-Petrol-Fuel-Oil-Pump-512.png",
		p2:"Gasoline",
		info3:"https://pic.onlinewebfonts.com/svg/img_128549.png",
		p3:"5.3km/lit.",
		info4:"https://cdn3.iconfinder.com/data/icons/driver-wheel/154/car-auto-drive-driver-wheel-512.png",
		p4:"Automatic",
		image: "https://www.motorbiscuit.com/wp-content/uploads/2021/02/2021-Cadillac-Escalade-071.jpg",
		price: "$530/month",
	},
	{
		id: 5,
		name: "BMW 4 Series GTI",
		info1:"https://static.vecteezy.com/system/resources/previews/000/643/326/original/vector-group-people-icon.jpg",
		p1:"    4People",
		info2:"https://cdn0.iconfinder.com/data/icons/jumpicon-energy-glyph/32/-_Gas-Station-Petrol-Fuel-Oil-Pump-512.png",
		p2:"Gasoline",
		info3:"https://pic.onlinewebfonts.com/svg/img_128549.png",
		p3:"5.3km/lit.",
		info4:"https://cdn3.iconfinder.com/data/icons/driver-wheel/154/car-auto-drive-driver-wheel-512.png",
		p4:"Automatic",
		image: "https://cdn.motor1.com/images/mgl/BVpXj/s1/2018-bmw-4-series-gran-coupe.jpg",
		price: "$530/month",
	},
	{
		id: 6,
		name: "BMW 4 Series",
		info1:"https://static.vecteezy.com/system/resources/previews/000/643/326/original/vector-group-people-icon.jpg",
		p1:"    4People",
		info2:"https://cdn0.iconfinder.com/data/icons/jumpicon-energy-glyph/32/-_Gas-Station-Petrol-Fuel-Oil-Pump-512.png",
		p2:"Gasoline",
		info3:"https://pic.onlinewebfonts.com/svg/img_128549.png",
		p3:"5.3km/lit.",
		info4:"https://cdn3.iconfinder.com/data/icons/driver-wheel/154/car-auto-drive-driver-wheel-512.png",
		p4:"Automatic",
		image: "https://s3-eu-west-1.amazonaws.com/eurekar-v2/uploads/images/original/4coupeside.jpg",
		price: "$490/month",
	},

];

export default data;
